name: ROS 2 CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble

      - name: Install dependencies
        run: |
          rosdep update
          rosdep install --from-paths src -i -y --rosdistro humble || true

      - name: Build
        run: |
          source /opt/ros/humble/setup.sh
          colcon build

      - name: Test
        run: |
          source install/setup.sh
          colcon test
          colcon test-result --verbose

